apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ggg
  name: app1
  labels:
    service_type: testing
    service_name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      service_name: app1
  template:
    metadata:
      labels:
        service_type: backend
        service_name: app1
    spec:
      serviceAccountName: app1
      containers:
      - name: app1
        image: registry.gbesar.link/testing/app1:1c0f377
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        ## GENERAL ##
        - name: PORT
          value: "80"
        - name: PORT_TEST
          value: "80"
        - name: NODE_ENV
          value: "test"
      imagePullSecrets:
      - name: harbor-registry-secret