bases:
  - ../components/service

resources:
  - deployment.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: ggg
    target:
        kind: ServiceAccount
        name: service
    
  - patch: |-
      - op: replace
        path: /metadata/name
        value: ggg
      - op: replace
        path: /metadata/namespace
        value: ggg
      - op: replace
        path: /metadata/labels/service_type
        value: testing
      - op: replace
        path: /metadata/labels/service_name
        value: ggg
      - op: replace
        path: /spec/ports/0/port
        value: 80
      - op: replace
        path: /spec/selector/service_name
        value: ggg
    target:
        kind: Service
        name: service