apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: php:7.4-apache
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              valueFrom:
                secretKeyRef:
                  name: message-from-vault
                  key: message
          volumeMounts:
            - name: config-html
              mountPath: /var/www/html
            - name: message-from-vault-secret-volume
              mountPath: /etc/secret
      volumes:
        - name: config-html
          configMap:
            name: webserver-configmap
        - name: message-from-vault-secret-volume
          secret:
            secretName: message-from-vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-configmap
data:
  index.php: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Environment Variables</title>
    </head>
    <body>
      <h1>Environment Variables:</h1>
      <ul>
        <li><strong>MESSAGE:</strong> <?php print "".getenv("MESSAGE")."\n"; ?></li>
        <li><strong>MESSAGE FROM CONFIGMAP:</strong> <?php echo file_get_contents('/etc/secret/message'); ?></li>
      </ul>
    </body>
    </html>
