bases:
  - ../../../components/secret
  - ../../../components/service

resources:
  - deployment.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app4
    target:
        kind: ServiceAccount
        name: service

  - patch: |-
      - op: replace
        path: /spec/provider/vault/server
        value: "http://172.20.2.226:8200"
      - op: replace
        path: /spec/provider/vault/path
        value: "secret/an-web/"
    target:
        kind: SecretStore
        name: vault-backend

  - patch: |-
      - op: replace
        path: /spec/target/name
        value: message-from-vault
      - op: replace
        path: /spec/data/0/secretKey
        value: message
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: message
      - op: replace
        path: /spec/data/0/remoteRef/property
        value: message
    target:
        kind: ExternalSecret
        name: my-cool-secret

  - patch: |-
      - op: replace
        path: /metadata/name
        value: app4-staging
      - op: replace
        path: /metadata/namespace
        value: ggg
      - op: replace
        path: /metadata/labels/service_type
        value: testing
      - op: replace
        path: /metadata/labels/service_name
        value: app4-staging
      - op: replace
        path: /spec/ports/0/port
        value: 80
      - op: replace
        path: /spec/selector/service_name
        value: app4-staging
    target:
        kind: Service
        name: service

  - patch: |-
      - op: replace
        path: /metadata/name
        value: app4-staging-ing-org
      - op: replace
        path: /metadata/namespace
        value: ggg
      - op: replace
        path: /spec/rules/0/host
        value: app4-staging.link2.gbesar.link
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: app4-staging
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 80
    target:
        kind: Ingress
        name: ggg-ing-org