apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-cool-secret
spec:
  refreshInterval: "3s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: my-cool-new-secret #name of k8s secret
    creationPolicy: Owner #will be automatically create or delete on k8s
  data:
    - secretKey: username #k8s secret form name
      remoteRef:
        key: db #path on Vault
        property: username #form name on Vault
    - secretKey: password
      remoteRef:
        key: db 
        property: password