apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://172.20.2.226:8200"
      path: "secret/an-web/"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"